services:
  - type: web
    name: resume_project
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker"
    workingDirectory: backend
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false   # Don't write value to repo
      - key: DATABASE_URL
        fromDatabase:
          name: my-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: my-redis
          type: redis

  - type: worker
    name: celery-worker
    env: python
    buildCommand: "./build.sh"
    startCommand: "celery -A core worker --loglevel=info"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: my-redis
          type: redis

databases:
  - name: my-db
    plan: free

services:
  - type: redis
    name: my-redis
    ipAllowList: []
    plan: free
